brews:
  - repository:
      owner: sanriodev
      name: homebrew-goji
      branch: brew-releases/{{ .Version }}
      # token: '{{ .Env.TOKEN }}'
    custom_block: |
      test do
        output = shell_output("#{bin}/goji -n")
        assert_match(/Use arrow keys to select and press Enter to confirm\./, output)
      end
    commit_author:
      name: Matteo Juen
      email: matteo.juen@ematric.com
    folder: Formula
    homepage: 'https://github.com/sanriodev/goji'
    description: 'Lightweight version of Oji text emoticon generator. Rewritten in go'
    license: 'MIT'
