brews:
  - repository:
      owner: sanriodev
      name: goji-brewtap
      branch: brew-releases/{{ .Version }}
      token: '{{ .Env.TOKEN }}'
    commit_author:
      name: goreleaserbot
      email: goreleaserbot@example.com
    folder: Formula
    homepage: 'https://github.com/sanriodev/goji'
    description: 'goji binaries for brew.'
    license: 'MIT'
