brews:
  - repository:
      owner: sanriodev
      name: homebrew-goji
      branch: brew-releases/{{ .Version }}
      # token: '{{ .Env.TOKEN }}'
    commit_author:
      name: Matteo Juen
      email: matteo.juen@ematric.com
    folder: Formula
    homepage: 'https://github.com/sanriodev/goji'
    description: 'goji binaries for brew.'
    license: 'MIT'
