name: Release
on:
  push:
    tags:
      - '*'

permissions:
  contents: write
brews:
  - tap:
      owner: sanriodev
      name: goji-brewtap
    folder: Formula
    homepage: 'https://github.com/sanriodev/goji'
    description: 'goji binaries for brew.'
    license: 'MIT'
jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Fetch all tags
        run: git fetch --force --tags

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23'

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v5
        with:
          distribution: goreleaser
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Upload assets
        uses: actions/upload-artifact@v3
        with:
          name: goji
          path: ./out
