name: Create Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  create_release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up GitHub CLI
        uses: actions/setup-gh@v2

      - name: Authenticate GitHub CLI
        run: gh auth login --with-token <<< "${{ secrets.GITHUB_TOKEN }}"

      - name: Create GitHub Release
        id: create_release
        run: gh release create ${{ github.ref }} --title "Release ${{ github.ref }}" --notes "Release ${{ github.ref }}"

      - name: Upload Release Asset
        run: gh release upload ${{ github.ref }} path/to/your/asset
